### ISSUE TITLE
UnboundLocalError: local variable 'db' referenced before assignment

### ISSUE THREAD

**Issue by tstupka** [hifiberry/hifiberry-dsp#42]
Traceback (most recent call last):
  File "/usr/local/bin/dsptoolkit", line 29, in <module>
    cmdline.main()
  File "/usr/local/lib/python3.7/dist-packages/hifiberrydsp/dsptoolkit.py", line 1021, in main
    self.command_map[cmd]()
  File "/usr/local/lib/python3.7/dist-packages/hifiberrydsp/dsptoolkit.py", line 653, in cmd_set_rew_filters_both
    self.set_iir_filters(mode=MODE_BOTH, format=REW)
  File "/usr/local/lib/python3.7/dist-packages/hifiberrydsp/dsptoolkit.py", line 595, in set_iir_filters
    self.dsptk.get_samplerate())
  File "/usr/local/lib/python3.7/dist-packages/hifiberrydsp/parser/rew.py", line 112, in readfilters
    logging.info("Filter NO fc=%s", fc, db)
UnboundLocalError: local variable 'db' referenced before assignment

**Comment by tstupka** [comment]
also note the `gaion` typo in `REWPArser.readfilters: ... /logging.info("Filter EQ fc=%s, q=%s, gaion=%s, fs=%s`
