### ISSUE TITLE
dsptoolkit get-meta is broken: UnboundLocalError

### ISSUE THREAD

**Issue by jedie** [hifiberry/hifiberry-dsp#47]
```
# dsptoolkit get-meta
Traceback (most recent call last):
  File "/bin/dsptoolkit", line 29, in <module>
    cmdline.main()
  File "/usr/lib/python3.9/site-packages/hifiberrydsp/dsptoolkit.py", line 1049, in main
  File "/usr/lib/python3.9/site-packages/hifiberrydsp/dsptoolkit.py", line 748, in cmd_get_meta
UnboundLocalError: local variable 'attribute' referenced before assignment
```

It's v0.20 on HiFiBerryOS version: 20220826
```
# python
Python 3.9.7 (default, Aug 25 2022, 07:12:44) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hifiberrydsp
>>> hifiberrydsp.__version__
'0.20'
```

**Comment by hifiberry** [comment]
You need to use the attribute name that you want to get, e.g.

dsptoolkit get-meta balanceRegister
